### PR TITLE
packages mariadb: bump mariadb versions

### PR DESCRIPTION
**Pull request by HashidaTKS**

### CODE REVIEW

**Comment by komainu8** [comment]
Could you version up release version of Mroonga package like https://github.com/mroonga/mroonga/commit/21bc19685d7605210a9f4d1b1527149ae638b640#diff-42eb71b6a4a0256fd04202798dccadf2bd5e9d0330ea32f6b9870b3230ea89f1L27.

**Comment by komainu8** [comment]
Could you add change log like https://github.com/mroonga/mroonga/commit/21bc19685d7605210a9f4d1b1527149ae638b640#diff-42eb71b6a4a0256fd04202798dccadf2bd5e9d0330ea32f6b9870b3230ea89f1R130-R133?

**Comment by HashidaTKS** [comment]
@komainu8 

Thank you for your review!

I have addressed your comments.

> If we don't update the release version of the package, Mroonga users can't use the new package. Because if the release version is same new package and old package, yum or dnf can't detect new package.

Please let me confirm my understanding about this.
When MariaDB version is updated for a certain Mroonga version, we need update the release version in these `spec.in` files.
When Mroonga version is updated, the release version is reset to 1.
Is it right?

**Comment by komainu8** [comment]
> When Mroonga version is updated, the release version is reset to 1. Is it right?

Yes, it is.
The release version of Mroonga package is reset when Mroonga releases.

**Comment by HashidaTKS** [comment]
> Yes, it is.
> The release version of Mroonga package is reset when Mroonga releases.

I see. Thanks!

**Comment by HashidaTKS** [comment]
@komainu8 

May I merge this?

**Comment by HashidaTKS** [comment]
Thanks!

**Pull request merged**
