### PR TITLE
Add test for ubuntu jammy

### PR DESCRIPTION
**Pull request by HashidaTKS**

### CODE REVIEW

**Comment by HashidaTKS** [comment]
https://github.com/HashidaTKS/mroonga/runs/7494416988?check_suite_focus=true#step:5:59

Action `Test` filed because the URL to `wget` is not found.
It seems that the URL should be `https://packages.groonga.org/ubuntu/groonga-apt-source-latest-jammy.deb` , not `https://packages.groonga.org/debian/groonga-apt-source-latest-jammy.deb`

> wget https://packages.groonga.org/debian/groonga-apt-source-latest-jammy.deb

**Comment by kou** [comment]
We need to use https://launchpad.net/~groonga/+archive/ubuntu/ppa instead of https://packages.groonga.org/ for Ubuntu: https://mroonga.org/docs/install/ubuntu.html

**Comment by kou** [comment]
Sorry. We should use https://packages.groonga.org/ here.

**Comment by HashidaTKS** [comment]
Thanks, in my understanding, We need to use https://packages.groonga.org/ here because it is used to solve dependencies, but for install old_package, I think we also need to use https://launchpad.net/~groonga/+archive/ubuntu/ppa for Ubuntu.

https://github.com/mroonga/mroonga/blob/master/packages/apt/test.sh#L137

**Comment by HashidaTKS** [comment]
The CI failed with `Error 2 opening /vagrant/packages/mysql-8.0-mroonga/apt/repositories/ubuntu/pool/jammy/main/*/*/*_amd64.deb: No such file or directory`.
It seems that we should specify `/vagrant/packages/mysql-8.0-mroonga/apt/repositories/ubuntu/pool/jammy/universe/*/*/*_amd64.deb` because mroonga uses the `universe` repository for Ubuntu.

**Comment by kou** [comment]
If we use PPA, we should not use packages.groogna.org here. PPA packages must not depend on packages.groonga.org.

**Comment by kou** [comment]
Yes. We use `universe` for Ubuntu: https://github.com/apache/arrow/blob/master/dev/tasks/linux-packages/apt/build.sh#L43

**Comment by HashidaTKS** [comment]
> If we use PPA, we should not use packages.groogna.org here. PPA packages must not depend on packages.groonga.org.

I'm not sure about it (sorry for my ignorance), don't we need to use `packages.groogna.org` when we create the local apt repository ?

> reprepro includedeb ${code_name} \
>  ${repositories_dir}/${distribution}/pool/${code_name}/${repository_component}/*/*/*_{${architecture},all}.deb

https://github.com/mroonga/mroonga/blob/master/packages/apt/test.sh#L68

**Comment by kou** [comment]
The local APT repository only contains packages built by local. It doesn't depend on packages on packages.groogna.org.

**Comment by HashidaTKS** [comment]
> The local APT repository only contains packages built by local. It doesn't depend on packages on packages.groogna.org.

I see. Thank you!

**Comment by HashidaTKS** [comment]
Action reached to step to execute `./mtr` but it failed with the following error.

> mysql-test-run: *** ERROR: Could not find /usr/bin/mysql_keyring_encryption_test

https://github.com/HashidaTKS/mroonga/runs/7534963490?check_suite_focus=true#step:5:1556

**Comment by kou** [comment]
Could you install `mysql-testsuite-8.0`?

```console
$ apt-file search bin/mysql_keyring_
mysql-testsuite-8.0: /usr/lib/mysql-test/bin/mysql_keyring_encryption_test
```

**Comment by HashidaTKS** [comment]
I had added a change to install `mysql-testsuite-8.0`, but a process for installing `mysql-testsuite-8.0` already exist, so I have reverted it.

https://github.com/HashidaTKS/mroonga/runs/7534963490?check_suite_focus=true#step:5:1099
https://github.com/HashidaTKS/mroonga/runs/7534963490?check_suite_focus=true#step:5:1150

**Comment by HashidaTKS** [comment]
Maybe a working directory or something about path is wrong.
I am investigating...

**Comment by HashidaTKS** [comment]
> mysql-test-run: *** ERROR: Could not find /usr/bin/mysql_keyring_encryption_test

This error is solved by specifying the `--client-bindir` option to `mtr`, but another error has occurrd...

https://github.com/HashidaTKS/mroonga/runs/7537759878?check_suite_focus=true#step:5:1808

**Comment by kou** [comment]
Close in favor of #495.

**Pull request closed without merging**
