### PR TITLE
Fix mysql57-community-mroonga's installation issue.

### PR DESCRIPTION
**Pull request by yoku0825**
This is patch for #77 

  - Login and update password using same password string.
    Because of autogenerated password is expired by default.
  - INSTALL PLUGIN using autogenerated password.
  - Expire password for resetting to fresh installed environment.

### CODE REVIEW

**Comment by kou** [comment]
Thanks!!!

**Comment by yoku0825** [comment]
@kou I commented at https://github.com/mroonga/mroonga/commit/9f30d4da70b94a43a72debaa1b49760caa0f4eae#commitcomment-14066152

I use MYSQL_PWD with the intention!!

**Comment by yoku0825** [comment]
Because of that, export is necessary too...

**Comment by kou** [comment]
Thanks for your description.
Why did you choose environment variable approach instead of `--password=XXX` approach? Is it for security?

**Comment by yoku0825** [comment]
Because I couldn't determine auto-generated password doesn't have special -- this means which needs to be escaped -- characters for shell, single-quote and double-quote, back-quote.

MYSQL_PWD is free from this concern.

**Comment by kou** [comment]
Thanks. I understood.

(If auto generated password includes single quote or double quote, `"ALTER USER user() IDENTIFIED BY '$MYSQL_PWD'"` will report an error...)

**Comment by yoku0825** [comment]
Oops!? I missed to take care of that statement..
I will look for password generate function tomorrow..

**Comment by yoku0825** [comment]
I found generate password function is here.
https://github.com/mysql/mysql-server/blob/b4104b21520be032400b768cea09a867068be49d/sql/sql_initialize.cc#L81-L144

I seem '!' charset is metachar for bash event but using in variable is safe.

```
$ echo "abc!def12"
-bash: !def12": event not found

$ cat test
abc!def12

$ auto_generated_password=`cat test`
$ echo "$auto_generated_password"
```

Should I fix to use `mysql -p"$auto_generated_password"` ?

**Comment by kou** [comment]
Thanks for confirming it.

> Should I fix to use `mysql -p"$auto_generated_password"` ?

Yes, please! Because it's more explicit code rather than `MYSQL_PWD` environment variable.

**Comment by yoku0825** [comment]
I re-request as #79

**Pull request merged**
