### PR TITLE
Fix to Not using MYSQL_PWD

### PR DESCRIPTION
**Pull request by yoku0825**
Re-fix for #77 .
Discussions are in #78 comments.

### CODE REVIEW

**Comment by kou** [comment]
Thanks!
`eval` is needed?

**Comment by yoku0825** [comment]
No, I just follow line 158.
https://github.com/yoku0825/mroonga/blob/9f001e1cb8044383c15a9796ba3579c89e05e2a8/packages/rpm/centos/mysql57-community-mroonga.spec.in#L158

**Comment by kou** [comment]
I see.
Could you remove `eval`? Because the code is just for reusing command line string for output. In this case, we don't reuse command line string. So we don't need to use `eval`.

**Comment by kou** [comment]
I've merged it because I heard `eval` is needed from @yoku0825.

**Comment by yoku0825** [comment]
I was failing without `eval` but I can determine where causes a problem at last.
I tried `$auto_generated_password` to set like `-p"$auto_generated_password"`, this was mishandled in script.

**Pull request merged**
