### PR TITLE
doc mroonga_highlight_html: add document about target_type option

### PR DESCRIPTION
**Pull request by HashidaTKS**
#544

### CODE REVIEW

**Comment by HashidaTKS** [comment]
@kou, @komainu8 

Would you review this when you have time?

@yoshimotoyuk

Would you review this about English when you have time?

**Comment by kou** [comment]
Should we finish #540 before we work on this?
If we change the specification for `target_type` in #540, we need to rewrite this.

**Comment by HashidaTKS** [comment]
> Should we finish https://github.com/mroonga/mroonga/pull/540 before we work on this?

I see.
Please wait the review until https://github.com/mroonga/mroonga/pull/540 is finished.

**Comment by HashidaTKS** [comment]
A long time has passed since this PR was created.

I think we should re-consider this again from the beginning.
We can discuss about this in https://github.com/mroonga/mroonga/issues/536

**Pull request closed without merging**
