### PR TITLE
test: suppress warning since 10.3.18/10.4.8

### PR DESCRIPTION
**Pull request by kenhys**
Warnings:
  Warning	1280	Name 'property' ignored for PRIMARY key.

### CODE REVIEW

**Comment by kou** [comment]
We should just remove `property` instead of ignoring warning.

**Comment by kenhys** [comment]
Thanks,　I've fixed it.

**Comment by kou** [comment]
Why do `--disable_warnings` and `--enable_warnings` still exist?

**Comment by kou** [comment]
I think that we need to change `.result` too.

**Comment by kenhys** [comment]
> Why do --disable_warnings and --enable_warnings still exist?

Surely removed at the same time.

https://github.com/mroonga/mroonga/commit/534050c2c8b0656ffce3b9634892d4a9252a2226

**Comment by kou** [comment]
Sorry. I missed it.

**Pull request merged**
